# This file describes an application. You can have multiple applications
# in the same project.

# The name of this app. Must be unique within a project.
name: app

# The type of the application to build.
type: php:7.1
build:
    flavor: composer

# The configuration of app when it is exposed to the web.
web:
    commands:
        # This is the command to start the AmPHP/Aerys PHP server.
        start: php vendor/bin/aerys -c aerys.php
    # We need to explicitly force Platform.sh to expose a TCP socket to
    # the application, in the PORT environment variable.
    upstream:
        socket_family: tcp
        protocol: http
    locations:
        /:
            root: public
            scripts: false
            allow: true
            index:
                - index.html
        /ws:
            passthru: true

# The size of the persistent disk of the application (in MB).
disk: 512
