"http://{default}/":
    type: upstream
    upstream: "app:http"
    cache:
        enabled: false

"http://{default}/ws":
    type: upstream
    upstream: "app:http"
    cache:
        enabled: false
